---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
   - name: ubuntu-16.04
#  - name: centos-7.2
#  - name: centos73
#    driver:
#      image: centos:7.3.1611
verifier:
  name: inspec
        
suites:
  - name: default
    run_list:
      - recipe[my_cookbook::default]
    attributes:
